name: QuestManager
main: nmt.minecraft.QuestManager.QuestManagerPlugin
version: 1.0
softdepend: [Fanciful, Multiverse-Core]
loadfirst:
permissions:
    questmanager.admin:
        description: The permission to do plugin-critical things like reload
        default: op
commands:
    questlog:
        usage: /questlog
        description: Gives or updates the player's quest log
    qmchatmenu:
        usage: This command is not meant to be called directly.
        description: Internal interface command for quest menus - chat
    party:
        usage: /party
        description: used to interface with the party menus
        aliases: p
    questmanager:
        usage: /questmanager [reload]
        description: QuestManager admin command
        permission: questmanager.admin